# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#relative_permalinks: false

# Setup
title:               "frpsug"
tagline:             'Groupe d'utilisateurs PowerShell francophone'
description:         'test'
url:                 http://frpsug.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              X
  url:               https://twitter.com/frpsug
  email:             frpsug@gmail.com

# Custom vars
version:             1.0.0
